name: An R workflow to automate regional changes csv and graphs
on:
        schedule:
                - cron: '30 2 * * *'

jobs: 
        build:
                name: R github actions
                runs-on: ubuntu-latest
                steps: 
                        - uses: actions/checkout@master
                        - uses: r-lib/actions/setup-r@master
                          with: 
                                  r-version: '3.5.3' # The R version to be installed 
                        - name: Install dependencies        
                          run: |
                             source <(curl -s https://raw.githubusercontent.com/saptahash/test_repo/master/regionalchanges/sysrequirements.sh)
                        - name: Run regional changes updates code
                          run: | 
                            cd regional_changes
                            ls
                            echo 'Starting data prep code'
                            Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/saptahash/test_repo/master/regionalchanges/latest_regions.R")'
                        - name: Commit changes
                          run: |
                            ls
                            echo 'Committing output'
                            git config --local user.email "action@github.com"
                            git config --local user.name "GitHub Action"
                            git add .
                            git diff-index --quiet HEAD || git commit -m "Adding latest csv and images for regional changes" -a
                        - name: Push changes
                          uses: ad-m/github-push-action@master
                          with:
                            github_token: ${{ secrets.GITHUB_TOKEN }}
