name: An R workflow to automate regional changes outputs
on:
#  push
  schedule:
    - cron: '30 4 * * *'

jobs:
  build:
    name: R github actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          path: master

      - uses: r-lib/actions/setup-r@master

      - name: Cache R packages
        uses: actions/cache@main
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          ls
          cd master
          ls
          chmod +x ./r-code/sysrequirements.sh
          ./r-code/sysrequirements.sh

      - name: Run regional changes updates code
        run: |
          ls
          cd master
          ls
          cd regional_changes
          chmod +x '../r-code/latest_regions.R'
          Rscript '../r-code/latest_regions.R'

      - name: Commit changes
        run: |
          ls
          cd master
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated run of regional reports" -a
          git push origin master:master
